[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "yaiv"
dynamic = ["version"]
authors = [
{ name = "Martin Gutierrez-Amigo", email = "martin.gutierrez.amigo@gmail.com" }
]
description = "Yet another Ab Initio Visualizer with a variety of tools"
readme = "README.md"
dependencies = [
    "matplotlib",
    "pint",
    "ase",
    "spglib",
    "scipy",
]
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)"
]

[project.urls]
Homepage = "https://github.com/mgamigo/YAIV"
"Bug Tracker" = "https://github.com/mgamigo/YAIV/issues"

[tool.setuptools.dynamic]
version = {attr = "yaiv.__version__"}

[tool.setuptools.packages.find]
exclude = ["tests*", "docs*"]

[tool.setuptools.package-data]
yaiv = ["defaults/extra_units.txt"]

[project.optional-dependencies]

notebook = [
    "ipympl",
    "nglview==3.1.4",
]
